n = 15
(
    SELECT_LANG,
    SEND_NAME,
    SEND_CONTACT,
    CLICK_LANG,
    ALL_SETTINGS,
    LANG_SETTINGS,
    NAME_SETTINGS,
    PHONE_SETTINGS,
    ANSWERING,
    TYPE_POST_NUMBER,
    ASK_PAYMENT,
    VACANCY_ACTIONS,
    CHANGING,
    CHANGE_PAYMENT,
    GET_TEXT_VACANCY,
) = range(0, n)
